name: 'Build LocalAI ZTA image'

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: write
  security-events: write
  id-token: write
  actions: read
jobs:
  stage-1:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: ./images/stage-1/Dockerfile
          tags: quay.io/mauromorales/localai-zta:${{ github.sha }}-stage-1
          labels: "quay.expires-after=2d"
          push: true
  localai-zta:
    name: Kairos Factory
    needs: stage-1
    uses: kairos-io/kairos-factory-action/.github/workflows/reusable-factory.yaml@v0.0.8
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    with:
      base_image: quay.io/mauromorales/localai-zta:${{ github.sha }}-stage-1
      dockerfile_path: ./images/stage-2/Dockerfile
      model: "generic"
      arch: "amd64"
      version: "v0.0.1"
      iso: true
      grype: true
      registry_domain: "quay.io"
      registry_namespace: "mauromorales"
      registry_repository: "localai-zta"
      summary_artifacts: true
      # kubernetes_distro: "k0s"
      # kubernetes_version: "v1.33.3+k0s.0"
      custom_tag_format: "$VERSION"
      custom_artifact_format: "localai-zta-$VERSION"
      custom_job_name_format: "localai-zta"
      cloud_config: ./cloud-config.yaml
      image_labels: "quay.expires-after=2d"